# -*- coding: utf-8 -*-
"""topsis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HEQTBhC8U7Qgz_QtMVsF50b_sUxjNA-M
"""

install.packages("readxl")
install.packages("readr")
install.packages("topsis")
install.packages("dplyr")

args <- commandArgs(trailingOnly = TRUE)

if(length(args) != 4) {
  cat("Error: Expected 4 arguments: <InputDataFile> <Weights> <Impacts> <OutputResultFileName>\n")
  cat("Example: Rscript topsis.R data.csv \"1,1,1,2\" \"+,+,-,+\" result.csv\n")
  quit(status=1)
}

input_file <- args[1]
weights_str <- args[2]
impacts_str <- args[3]
output_file <- args[4]

# 1. Check file exists
if (!file.exists(input_file)) {
  cat("Error: Input file not found.\n")
  quit(status=1)
}
# 2. Read input data - SUPPORTS CSV + XLSX
if (tools::file_ext(input_file) == "csv") {
  data <- read_csv(input_file, show_col_types = FALSE)
} else if (tools::file_ext(input_file) == "xlsx") {
  data <- readxl::read_excel(input_file)
} else {
  cat("Error: Input file must be .csv or .xlsx\n")
  quit(status=1)
}


# 3. Check minimum 3 columns
if (ncol(data) < 3) {
  cat("Error: Input file must contain at least 3 columns (1 identifier + ≥2 criteria).\n")
  quit(status=1)
}

# 4. Check columns 2+ are numeric
criteria_cols <- 2:ncol(data)
if (!all(sapply(data[, criteria_cols], is.numeric))) {
  cat("Error: Non-numeric value found in criteria columns (from 2nd to last column).\n")
  quit(status=1)
}

n_criteria <- length(criteria_cols)

# 5. Parse weights
weights <- as.numeric(strsplit(weights_str, ",")[[1]])
if (length(weights) != n_criteria || any(is.na(weights))) {
  cat("Error: Weights must be numeric and comma-separated.\n")
  quit(status=1)
}

# Normalize weights
weights <- weights / sum(weights)

# 6. Parse impacts
impacts <- strsplit(impacts_str, ",")[[1]]
impacts <- toupper(trimws(impacts))
if (length(impacts) != n_criteria ||
    !all(impacts %in% c("+", "-"))) {
  cat("Error: Impacts must be '+' or '-' only, separated by commas.\n")
  quit(status=1)
}

cat("Running TOPSIS...\n")

# === TOPSIS ALGORITHM ===
library(Topsis)

# Adjust these 2 lines based on your package:
result_data <- topsis(  # ← YOUR PACKAGE FUNCTION
  matrix = as.matrix(data[, criteria_cols]),
  weights = weights,
  type = impacts
)

# Reconstruct full output (keeps original format)
colnames(result_data) <- c(colnames(data)[criteria_cols], "Topsis Score")
result_df <- cbind(data[, 1, drop=FALSE], result_data)
result_df$Rank <- rank(-result_df[["Topsis Score"]])

# Save output
write_csv(result_df, output_file, na="")
cat(sprintf("Output saved to: %s\n", output_file))